apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: votre-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/votreusername/votre-repo.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
